### ISSUE TITLE
Add wording about using game screenshots, fine print. 

### ISSUE THREAD

**Issue by pramslam** [indiegamecon/indiegamecon-gatsby#103]
When submitting a game, have a checkbox to acknowledge disclaimer..

Bitforest reserves the right to use any photograph/video/screenshot taken at any event sponsored by Bitforest, without the expressed written permission of those included within the photograph/video/screenshot. Bitforest may use the photograph/video/screenshot in publications or other media material produced, used or contracted by Bitforest including but not limited to: brochures, invitations, books, newspapers, magazines, television, websites, etc.

**Comment by mckelveygreg** [comment]
I was working on this, this morning, but I couldn't decide on how to display the terms. 
I'll be able to work on it a little later this week!

**Comment by mckelveygreg** [comment]
finally added this!! #105 
Close this out, and merge if you like it!
