### ISSUE TITLE
Game submission

### ISSUE THREAD

**Issue by pramslam** [indiegamecon/indiegamecon-gatsby#11]
- [x] Remove question on questionnaire
- [x] Formatting questions questionnaire
- [x] Confirmation Page that links to ticket purchasing.
- [x] Event submission guidelines editable in markdown

1. In the questionnaire, please remove "which days are you attending?"

2. Add colon to Team Name, Game Name

3. I would like, once a game a submitted, it gives them a confirmation code then takes them to a confirmation page that instructs them to buy their tickets through an eventbrite link. It should say something like:

>  Thank you so much **Name* for submitting your game to Indie Game Con! The next step is to buy your Exclusive Game Dev Pass! When purchasing, use code GAMEDEV2019, to get your discounted ticket.

> Confirmation: XXXXX
> You will need this number when purchasing your Exclusive Game Dev Pass!

4. I would like to put to some game submission guidelines text at the top of the Game submission page before the submission button, preferably editable in markdown?

**Comment by mckelveygreg** [comment]
For the confirmation number, is that something that eventbrite will need to give or identify? If I generate a random code, does eventbrite need to know what it is, or do they have codes already that we would need to use?

**Comment by mckelveygreg** [comment]
Form is corrected, question removed, and you can update the rules in the [games.md](https://github.com/mckelveygreg/indiegamecon-gatsby/blob/master/src/markdown/games.md) file! I love TODO lists like these, thanks!

**Comment by pramslam** [comment]
My goal with the confirmation number is to allow teams to register together, prevent things like double game submissions and prevent non-devs from buying a dev pass. I was thinking we can do this by tieing a submitted game to specific tickets through a confirmation number. I don't know if this is the best way.

Eventbrite won't generate a number for this purpose. But they allow required questions to be answered. I was going to make a confirmation number required when you buy a game dev ticket. Though there's no way to automagically check if the number is valid when they enter it.

I'd like to talk about this more in person at TechTuesday if you're there.

**Comment by pramslam** [comment]
Solved with confirmation box and manual checking of each game submission
