### ISSUE TITLE
Developers/Games Pages

### ISSUE THREAD

**Issue by websupergirl** [indiegamecon/indiegamecon-gatsby#111]
This is confusing as a user. The chunk at the top of games should be on a reg page because it's close to the event and people are looking to see what games will be there ... but it's at the bottom of a very long list. 

I'm also confused of the list of people on the developers page vs the list of games ... why?

I think we should move the chunk about registration from the games page to the bottom of the developers page. Also add all the developers list from the games page to the developers page.

And then update the games page with any new submissions.

**Comment by pramslam** [comment]
Yes, that sounds awesome! Thank you!

**Comment by websupergirl** [comment]
Is there a list of new submissions?

**Comment by mckelveygreg** [comment]
Every time the site is rebuilt, it grabs from airtable, so whatever is new there gets incorporated. 
hmm, those will only populate on your machine if you have airtable environment vars.... I can set you up with those if you would like
