### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by websupergirl** [indiegamecon/indiegamecon-gatsby#112]
The sponsors page needs to be updated with this years sponsors - please list them.

Also how to sponsor needs to be pushed down below this years sponsors.

**Comment by pramslam** [comment]
Sponsor Images
https://drive.google.com/open?id=1tIDsR2ATT4ZeLn9-i7mC7J6fwRXH2gzt

In this order:
First Call Resolution
Devolver
Pipeworks
Nulia
Eugene Parking
GlimmerTech
King Pong
EugeneTech
TAO
Toxic Wings
Bricks and Minifigs

**Comment by pramslam** [comment]
Forgot the bricks and minifigs logo
![unnamed](https://user-images.githubusercontent.com/10286614/67729502-8dca9380-f9ae-11e9-8d7a-3796ed89f515.png)

**Comment by websupergirl** [comment]
THANKS will do

**Comment by mckelveygreg** [comment]
This should be built and populated from airtable.

@pramslam is there different sponsorship levels that we should put on this page?

**Comment by websupergirl** [comment]
Is TAO the local one or Oregon TAO? I went with Oregon TAO.

**Comment by websupergirl** [comment]
@mckelveygreg This has been added to airtable with order being 3-digit number starting at 100. 

Level has been left off for now, pending info from @pramslam

**Comment by websupergirl** [comment]
@mckelveygreg I would like to see a grid of sponsors at the top, then the instructions on becoming a sponsor, and then special thanks to past sponsors.

So ...

```
A great big thank you to this year's sponsors!
[sponsor grid with icons and links]

-- divider --

Sponsorship FAQ
current info

-- divider --

Another thank you to our previous sponsors [previous sponsor list]
```

AND

Section that says 
```
How do you sponsor?
Indie Game Con is a Bitforest project. Bitforest is a fiscally-sponsored 501(c)3 nonprofit organization that instills an innovation culture in Oregon communities. If you would like to donate to Bitforest, make your check Payable to “Bitforest ℅ TAO Foundation” and note “Indie Game Con” in the memo.

If you do not need a 501(c)3 paper receipt, you can donate through our Eventbrite link: *insert bit.ly link
```
should be removed.

Replace with:
```
Donations
If you do not need a 501(c)3 paper receipt, you can donate through our Eventbrite link (https://www.eventbrite.com/e/indie-game-con-2019-tickets-67666180367).
```

**Comment by mckelveygreg** [comment]
@websupergirl Checkout #117

**Comment by mckelveygreg** [comment]
This should be built and populated from airtable
