### ISSUE TITLE
Schedule of Events

### ISSUE THREAD

**Issue by pramslam** [indiegamecon/indiegamecon-gatsby#118]
| Saturday | Sunday
-- | -- | --
10:00 | Opening Ceremonies - Trophy Reveal | Will Bucknum - Voice to Game
10:15 | Dan White - Pipeworks |  
11:00 | Damon Slye - Mad Otter Games | Dave Merrill - Pipeworks
noon |   |  
1:00 | DTW - Band | DTW - Band
2:00 | Joe Marushak - Garage Games | Mark Davis - King Pong
3:00 | Noah Gervais-Caldwell | Britt Brady - Doinksoft
4:00 | Mike Jones - Pipeworks | Paul Brian
5:00 | Jonathan Rosales - Digital Revolver | Closing Ceremonies - Trophies

**Comment by mckelveygreg** [comment]
do we have more details for each time slot? Do you want to add this to the /src/markdown/schedules.mdx ?

**Comment by pramslam** [comment]
We don't have details on what talks they are going to have.

**Comment by mckelveygreg** [comment]
alright, schedule is updated!
