### ISSUE TITLE
Needs Facebook Tags

### ISSUE THREAD

**Issue by websupergirl** [indiegamecon/indiegamecon-gatsby#119]
The preview image right now is MEH.

<img width="374" alt="igc-fb" src="https://user-images.githubusercontent.com/38568655/67806962-1b5ebf80-fa51-11e9-9118-0e30ae0615eb.PNG">

**Comment by mckelveygreg** [comment]
If someone can add the appropriate links as described here?
https://www.gatsbyjs.org/docs/add-seo-component/#gatsby-configjs 

Granted, I can, but later today

**Comment by websupergirl** [comment]
In header:

```
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Indie Game Con Eugene OR Nov 2-3 2019" />
<meta property="og:url" content="https://www.indiegamecon.com/" />
<meta property="og:site_name" content="Indie Game Con" />
```

**Comment by websupergirl** [comment]
@mckelveygreg will that method push it as OpenGraph?

**Comment by websupergirl** [comment]
I'm looking for (or making) an image.

**Comment by mckelveygreg** [comment]
all of this can be configured in `gatsby-config`.
perhaps we can just use the logo?

**Comment by websupergirl** [comment]
The logo is on white though so that needs to be sorted.

Also FB lint will need to be redone after this is live.

**Comment by mckelveygreg** [comment]
meta tags updated, and poster added.
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.indiegamecon.com
