### ISSUE TITLE
Media Page is missing

### ISSUE THREAD

**Issue by pramslam** [indiegamecon/indiegamecon-gatsby#6]
I'd like to put the previous year sponsor letters into that page.

**Comment by mckelveygreg** [comment]
Would you like to do it in markdown or just make a list of media on an airtable? Let me know, both are easily implemented

**Comment by pramslam** [comment]
Markdown should be good!

**Comment by mckelveygreg** [comment]
K, media markdown piped up. Follow the patter I used on the [Homepage](https://github.com/mckelveygreg/indiegamecon-gatsby/blob/master/src/markdown/home.md) for adding videos and images.
