### ISSUE TITLE
Homepage Center Heading

### ISSUE THREAD

**Issue by pramslam** [indiegamecon/indiegamecon-gatsby#8]
I'd like these headings to be centered.
"What is Indie Game Con"
"Where & When"

**Comment by mckelveygreg** [comment]
So, I made a class that theoretically can center whatever you want. So like if you have a single random thing you want centered, put the text in [ ] and after it, put a class in { } ...
Example: 
```
# [What is Indie Game Con?]{.center}

or 

[Super centered text]{.center}
```

**Comment by mckelveygreg** [comment]
if you want to center a lot of the same things, then I'll just write some css for that. Pretty much, if you have to do it more than twice...
