### ISSUE TITLE
Remove old Game Submissions

### ISSUE THREAD

**Issue by pramslam** [indiegamecon/indiegamecon-gatsby#98]
Remove the old joke game submissions. You can leave the the Panguin Games one. If not, nbd!

**Comment by mckelveygreg** [comment]
I went on to Airtable to remove the old submissions. Remember, anything you want to show up on the site, just check the confirm box and then do a new build by committing something in the repo!

**Comment by websupergirl** [comment]
This is also fixed with confirmed/unconfirmed and adding the year to game submissions.
